[build-system]
requires = ["setuptools>=42", "wheel", "numpy>=1.19.0,<2.0.0", "cython"]
build-backend = "setuptools.build_meta"

[project]
name = "cgoertzel"
description = "Python wrapper for the DTFT Goertzel Algorithm"
version = "0.1.0"
dependencies = [
    "numpy>=1.19.0,<2.0.0",
]
